#!/bin/sh

### BEGIN INIT INFO
# Provides:          readtemp
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts script to read via W1
# Description:       starts readtemp using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/sbin//readtemp.py
NAME=readtemp
DESC=readtemp

# Include readtemp defaults if available
if [ -f /etc/default/readtemp ]; then
	. /etc/default/readtemp
fi

test -x $DAEMON || exit 0

set -e

. /lib/lsb/init-functions

is_running () {
	if [ -f "/var/run/$NAME.pid" ]; then
		dpid="$(head -1 /var/run/$NAME.pid)"
		if /bin/kill -0 -- ${dpid} >/dev/null 2>&1; then
			return 0;
		else
			echo 'Stale pidfile, removing'
			rm -f /var/run/$NAME.pid
			return 1;
		fi
	else
		return 1;
	fi
	return 1;
}

case "$1" in
	start)
		echo -n "Starting $DESC: "
		# Check if the ULIMIT is set in /etc/default/readtemp
		if [ -n "$ULIMIT" ]; then
			# Set the ulimits
			ulimit $ULIMIT
		fi
		if ! is_running; then
			$DAEMON $DAEMON_OPTS
		else
			echo " already running!"
			exit 3;
		fi
		#start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
		#    --exec $DAEMON -- $DAEMON_OPTS || true
		echo "$NAME."
		;;

	stop)
		echo -n "Stopping $DESC: "
		#start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid \
		#    --exec $DAEMON || true
		if is_running; then
			/bin/kill -- "$(head -1 /var/run/$NAME.pid)"
		else
			echo " not running!"
			exit 3;
		fi
		echo "$NAME."
		;;

	restart|force-reload)
		echo -n "Restarting $DESC: "
		if is_running; then
			echo "stopping"
			/bin/kill -- "$(head -1 /var/run/$NAME.pid)"
			sleep 1;
		else
			echo "is not running!"
		fi
		echo "Starting..."
		$DAEMON $DAEMON_OPTS
		#start-stop-daemon --stop --quiet --pidfile \
		#    /var/run/$NAME.pid --exec $DAEMON || true
		# Check if the ULIMIT is set in /etc/default/readtemp
		#if [ -n "$ULIMIT" ]; then
		#	# Set the ulimits
		#	ulimit $ULIMIT
		#fi
		#start-stop-daemon --start --quiet --pidfile \
		#    /var/run/$NAME.pid --exec $DAEMON -- $DAEMON_OPTS || true
		echo "$NAME."
		;;

	status)
		status_of_proc -p /var/run/$NAME.pid "$DAEMON" readtemp && exit 0 || exit $?
		;;
	*)
		echo "Usage: $NAME {start|stop|restart|force-reload|status}" >&2
		exit 1
		;;
esac

exit 0
