#!/bin/sh
#
: <<=cut

=head1 NAME

environmental - Plugin to monitor electrocity usage from CT sensor connected to arduino 

=head1 APPLICABLE SYSTEMS

All Linux systems

=head1 CONFIGURATION

The following is default configuration

  [electrocity]
  user root
  env.pidfile /var/run/mqttrcv.pid
  


=head2 EXAMPLE WARNING AND CRITICAL SETTINGS
It is necessary to run mqttrcv.py to receive MQTT messages

=head1 INTERPRETATION


=head1 MAGIC MARKERS

  #%# family=auto
  #%# capabilities=autoconf


=head1 VERSION

  $Id$

=head1 BUGS


Otherwise none known

=head1 AUTHOR

Zej

=head1 LICENSE

BSD

=cut


. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
	if [ -r /proc/stat ]; then
		echo yes
		exit 0
	else
		echo no
		exit 0
	fi
fi


extinfo=""


if [ "$1" = "config" ]; then

	echo 'multigraph electrocity_irms'
	echo 'graph_title Electrocity Irms'
	#echo "graph_order tempout  tempin" $extinfo
	echo "graph_args --base 1000 -r -l 0"
	echo 'graph_vlabel Irms '
	echo 'graph_scale yes'
	echo 'graph_info This graph electrocity usage from CT sensor'
	echo 'graph_category environmental'
	echo 'graph_period second'
	echo "irms.draw AREA"
	echo "irms.min 0"
	echo "irms.type GAUGE"
	echo "irms.label Irms"

	echo 'multigraph electrocity_appower'
	echo 'graph_title Electrocity apparent power'
	#echo "graph_order tempout  tempin" $extinfo
	echo "graph_args --base 1000 -r -l 0"
	echo 'graph_vlabel W'
	echo 'graph_scale yes'
	echo 'graph_info This graph shows apparent power of sensing CT probe'
	echo 'graph_category environmental'
	echo 'graph_period second'
	echo "appower.draw LINE2"
	echo "appower.min 0"
	echo "appower.type GAUGE"
	echo "appower.label Apparent power"
	exit 0

elif [ "$1" = "test" ]; then
	exit 0;

fi

get_ctstats () 
{
	MQTTRCV_PID=${mqttrcv_pidfile:=/var/run/mqttrcv.pid}
	kill -HUP $(head -1 ${MQTTRCV_PID})
	sleep 2;
	irms="$(awk '{print $1;}' /tmp/ct.stats)"
	echo 'multigraph electrocity_irms'
	printf "irms.value %.2f\n" "${irms}"
	echo 'multigraph electrocity_appower'
	printf "appower.value %.2f\n" "$(echo ${irms}*230.00|bc -q)"

}

get_ctstats;

